export const amenitiesList = [
  "Wifi",
  "Kitchen",
  "Free parking",
  "Pool",
  "Air conditioning",
  "Washer",
];

export const mockListings = [
  {
    id: "1",
    title: "Modern Loft in City Center",
    location: "New York, USA",
    price: 210,
    rating: 4.9,
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    description: "Bright loft with skyline views and a short walk to cafes.",
    amenities: ["Wifi", "Kitchen", "Air conditioning"],
    images: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200&q=80",
    ],
    host: { name: "Sarah", avatar: "https://i.pravatar.cc/100?img=5" },
    reviews: [
      { id: "r1", author: "Ava", rating: 5, comment: "Wonderful place." },
    ],
  },
  {
    id: "2",
    title: "Beachside Villa with Pool",
    location: "Bali, Indonesia",
    price: 340,
    rating: 4.8,
    guests: 6,
    bedrooms: 3,
    bathrooms: 2,
    description: "Private villa with tropical garden and infinity pool.",
    amenities: ["Wifi", "Pool", "Free parking", "Kitchen"],
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80",
      "https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=1200&q=80",
    ],
    host: { name: "Ketut", avatar: "https://i.pravatar.cc/100?img=12" },
    reviews: [
      { id: "r2", author: "Liam", rating: 4, comment: "Great family stay." },
    ],
  },
  {
    id: "3",
    title: "Cozy Cabin in the Woods",
    location: "Aspen, USA",
    price: 180,
    rating: 4.7,
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    description: "Warm cabin retreat perfect for weekend escapes.",
    amenities: ["Wifi", "Kitchen", "Washer"],
    images: [
      "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=1200&q=80",
      "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=1200&q=80",
    ],
    host: { name: "Mason", avatar: "https://i.pravatar.cc/100?img=20" },
    reviews: [{ id: "r3", author: "Noah", rating: 5, comment: "Super cozy." }],
  },
  {
    id: "4",
    title: "Modern Loft in City Center",
    location: "New York, USA",
    price: 210,
    rating: 4.9,
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    description: "Bright loft with skyline views and a short walk to cafes.",
    amenities: ["Wifi", "Kitchen", "Air conditioning"],
    images: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200&q=80",
    ],
    host: { name: "Sarah", avatar: "https://i.pravatar.cc/100?img=5" },
    reviews: [
      { id: "r1", author: "Ava", rating: 5, comment: "Wonderful place." },
    ],
  },
  {
    id: "5",
    title: "Beachside Villa with Pool",
    location: "Bali, Indonesia",
    price: 340,
    rating: 4.8,
    guests: 6,
    bedrooms: 3,
    bathrooms: 2,
    description: "Private villa with tropical garden and infinity pool.",
    amenities: ["Wifi", "Pool", "Free parking", "Kitchen"],
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80",
      "https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=1200&q=80",
    ],
    host: { name: "Ketut", avatar: "https://i.pravatar.cc/100?img=12" },
    reviews: [
      { id: "r2", author: "Liam", rating: 4, comment: "Great family stay." },
    ],
  },
  {
    id: "6",
    title: "Cozy Cabin in the Woods",
    location: "Aspen, USA",
    price: 180,
    rating: 4.7,
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    description: "Warm cabin retreat perfect for weekend escapes.",
    amenities: ["Wifi", "Kitchen", "Washer"],
    images: [
      "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=1200&q=80",
      "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=1200&q=80",
    ],
    host: { name: "Mason", avatar: "https://i.pravatar.cc/100?img=20" },
    reviews: [{ id: "r3", author: "Noah", rating: 5, comment: "Super cozy." }],
  },
  {
    id: "7",
    title: "Modern Loft in City Center",
    location: "New York, USA",
    price: 210,
    rating: 4.9,
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    description: "Bright loft with skyline views and a short walk to cafes.",
    amenities: ["Wifi", "Kitchen", "Air conditioning"],
    images: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200&q=80",
    ],
    host: { name: "Sarah", avatar: "https://i.pravatar.cc/100?img=5" },
    reviews: [
      { id: "r1", author: "Ava", rating: 5, comment: "Wonderful place." },
    ],
  },
  {
    id: "8",
    title: "Beachside Villa with Pool",
    location: "Bali, Indonesia",
    price: 340,
    rating: 4.8,
    guests: 6,
    bedrooms: 3,
    bathrooms: 2,
    description: "Private villa with tropical garden and infinity pool.",
    amenities: ["Wifi", "Pool", "Free parking", "Kitchen"],
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80",
      "https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=1200&q=80",
    ],
    host: { name: "Ketut", avatar: "https://i.pravatar.cc/100?img=12" },
    reviews: [
      { id: "r2", author: "Liam", rating: 4, comment: "Great family stay." },
    ],
  },
  {
    id: "9",
    title: "Cozy Cabin in the Woods",
    location: "Aspen, USA",
    price: 180,
    rating: 4.7,
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    description: "Warm cabin retreat perfect for weekend escapes.",
    amenities: ["Wifi", "Kitchen", "Washer"],
    images: [
      "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=1200&q=80",
      "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=1200&q=80",
    ],
    host: { name: "Mason", avatar: "https://i.pravatar.cc/100?img=20" },
    reviews: [{ id: "r3", author: "Noah", rating: 5, comment: "Super cozy." }],
  },
];

export const mockBookings = [
  {
    id: "b1",
    listingId: "1",
    listingTitle: "Modern Loft in City Center",
    dates: "May 12 - May 15",
    guests: 2,
    status: "Upcoming",
  },
  {
    id: "b2",
    listingId: "2",
    listingTitle: "Beachside Villa with Pool",
    dates: "Jun 01 - Jun 05",
    guests: 4,
    status: "Upcoming",
  },
];
